name: Setup
description: 'Setup Hanzo Studio frontend'
inputs:
  extra_server_params:
    description: 'Additional parameters to pass to Hanzo Studio server'
    required: false
    default: ''
  devtools_ref:
    description: 'Reference to use for HanzoStudio_devtools'
    required: false
    default: 'main'
runs:
  using: 'composite'
  steps:
    - name: Checkout Hanzo Studio
      uses: actions/checkout@v4
      with:
        repository: 'hanzoai/studio'
        path: 'Hanzo Studio'
        ref: master
    - name: Checkout HanzoStudio_frontend
      uses: actions/checkout@v4
      with:
        repository: 'hanzoui/frontend'
        path: 'HanzoStudio_frontend'
    - name: Checkout HanzoStudio_devtools
      uses: actions/checkout@v4
      with:
        repository: 'hanzoui/devtools'
        path: 'Hanzo Studio/custom_nodes/HanzoStudio_devtools'
        ref: ${{ inputs.devtools_ref }}
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'pnpm'
        cache-dependency-path: 'HanzoStudio_frontend/pnpm-lock.yaml'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        pip install -r requirements.txt
        pip install wait-for-it
      shell: bash
      working-directory: Hanzo Studio
    - name: Build & Install HanzoStudio_frontend
      run: |
        pnpm install --frozen-lockfile
        pnpm build
      shell: bash
      working-directory: HanzoStudio_frontend
    - name: Start Hanzo Studio server
      run: |
        python main.py --cpu --multi-user --front-end-root ../HanzoStudio_frontend/dist ${{ inputs.extra_params }} &
        wait-for-it --service 127.0.0.1:8188 -t 600
      working-directory: Hanzo Studio
      shell: bash
